### ISSUE TITLE
Compile error: ‘write’ reading 18 bytes from a region of size 17

### ISSUE THREAD

**Issue by roman4e** [vysheng/tg#1763]
While compiling with gcc -v =11.2.0
got next error: 
`main.c:824:7: error: ‘write’ reading 18 bytes from a region of size 17 [-Werror=stringop-overread]
  824 |   if (write (1, "SIGNAL received\n", 18) < 0) {
`

String "SIGNAL received\n" has size 17.

**Comment by jimthedj65** [comment]
I did this today on Ubuntu 22.04 and got the same on GNU Make 4.3

**Comment by skadomsky** [comment]
Same bro. It also doen't work on Ubuntu 22.04 on my machine.

**Comment by simafrus** [comment]
Fedora 37, same

**Comment by AnatoliyZhurilo** [comment]
same

**Comment by Paulchen232** [comment]
try this:
with modified tg/Makefile and deleted -Werror
`nano Makefile`
`./configure`
`make`

**Comment by Paulchen232** [comment]
Or change main.c:824 18 -> 17
`./configure|
`make`

**Comment by dorsegal** [comment]
Anyone managed to solve this?

**Comment by usmanovbf** [comment]
unfortunately, didn't help even after advices from @Paulchen232 

```
uname -a
Linux ubuntu 5.15.0-87-generic #97-Ubuntu SMP Tue Oct 3 09:52:42 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by usmanovbf** [comment]
BTW, the strange behavior is that I don't have `libpython-dev` but I had to install `libpython2-dev`

```
sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev libjansson-dev libpython-dev make 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libpython-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libpython2-dev

E: Package 'libpython-dev' has no installation candidate
```
