### ISSUE TITLE
Error while doing make

### ISSUE THREAD

**Issue by M4RC0Sx** [vysheng/tg#1594]
Hi, I am installing it on debian and have followed all steps. When I try to make I get this error. I haven't modified any files. I am not able to fix that and get telegram-cli running.

tgl/crypto/rsa_pem_openssl.c: In function ‘TGLC_rsa_new’:
tgl/crypto/rsa_pem_openssl.c:41:6: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
   ret->e = unwrap_bn (TGLC_bn_new ());
      ^~
tgl/crypto/rsa_pem_openssl.c: In function ‘TGLC_rsa_n’:
tgl/crypto/rsa_pem_openssl.c:52:1: warning: control reaches end of non-void function [-Wreturn-type]
 RSA_GETTER(n);
 ^~~~~~~~~~
tgl/crypto/rsa_pem_openssl.c: In function ‘TGLC_rsa_e’:
tgl/crypto/rsa_pem_openssl.c:53:1: warning: control reaches end of non-void function [-Wreturn-type]
 RSA_GETTER(e);

**Comment by Paulchen232** [comment]
Do this:
`sudo apt-get install libssl1.0-dev`
And to redo `make'  

Am 21. April 2019 18:11:36 MESZ schrieb Marcos <notifications@github.com>:
>Hi, I am installing it on debian and have followed all steps. When I
>try to make I get this error. I haven't modified any files. I am not
>able to fix that and get telegram-cli running.>
>>
>>
>tgl/crypto/rsa_pem_openssl.c: In function ‘TGLC_rsa_new’:>
>tgl/crypto/rsa_pem_openssl.c:41:6: error: dereferencing pointer to
>incomplete type ‘RSA {aka struct rsa_st}’>
>   ret->e = unwrap_bn (TGLC_bn_new ());>
>      ^~>
>tgl/crypto/rsa_pem_openssl.c: In function ‘TGLC_rsa_n’:>
>tgl/crypto/rsa_pem_openssl.c:52:1: warning: control reaches end of
>non-void function [-Wreturn-type]>
> RSA_GETTER(n);>
> ^~~~~~~~~~>
>tgl/crypto/rsa_pem_openssl.c: In function ‘TGLC_rsa_e’:>
>tgl/crypto/rsa_pem_openssl.c:53:1: warning: control reaches end of
>non-void function [-Wreturn-type]>
> RSA_GETTER(e);>
>>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/vysheng/tg/issues/1594

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by nsklyarov** [comment]
> Do this: `sudo apt-get install libssl1.0-dev` and redo `make`.
doesnt work on ubuntu 19.04

**Comment by nsklyarov** [comment]
> Do this: `sudo apt-get install libssl1.0-dev` and redo `make`.

doesnt work on ubuntu 19.04

**Comment by TheTitanrain** [comment]
> doesnt work on ubuntu 19.04

Working on Ubuntu 19.04. Something wrong with your repos maybe.

**Comment by atul-indexnine** [comment]
> > Do this: `sudo apt-get install libssl1.0-dev` and redo `make`.
> 
> doesnt work on ubuntu 19.04
> 
> ```
> E: Package 'libssl1.0-dev' has no installation candidate
> ```

I am also facing same error. Did you solve it?

**Comment by Paulchen232** [comment]
Try this:

https://packages.debian.org/jessie/libssl-dev

**Comment by Paulchen232** [comment]
Or make this on and redo it.
![Bildschirmfoto von 2019-08-23 13-11-21](https://user-images.githubusercontent.com/24520281/63589112-8b138280-c5a8-11e9-8c4b-68daee8138da.png)
