### ISSUE TITLE
Build does not work on Ubuntu18.04 TLS

### ISSUE THREAD

**Issue by danuk** [vysheng/tg#1653]
How to reproduce:

```
 git clone --recursive https://github.com/vysheng/tg.git && cd tg

./configure
make
.....

tgl/crypto/rsa_pem_openssl.c: In function ‘TGLC_rsa_new’:
tgl/crypto/rsa_pem_openssl.c:41:6: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
   ret->e = unwrap_bn (TGLC_bn_new ());
      ^~
tgl/crypto/rsa_pem_openssl.c: In function ‘TGLC_rsa_n’:
tgl/crypto/rsa_pem_openssl.c:52:1: error: control reaches end of non-void function [-Werror=return-type]
 RSA_GETTER(n);
 ^~~~~~~~~~
tgl/crypto/rsa_pem_openssl.c: In function ‘TGLC_rsa_e’:
tgl/crypto/rsa_pem_openssl.c:53:1: error: control reaches end of non-void function [-Werror=return-type]
 RSA_GETTER(e);
 ^~~~~~~~~~
cc1: all warnings being treated as errors
Makefile.tgl:20: recipe for target 'objs/crypto/rsa_pem_openssl.o' failed
make: *** [objs/crypto/rsa_pem_openssl.o] Error 1

```

**Comment by Paulchen232** [comment]
You can try that:
`sudo apt-get install libssl1.0-dev`

**Comment by bizlevel** [comment]
https://github.com/rvm/rvm/issues/4764#issuecomment-524923070
https://github.com/rvm/rvm/issues/4764#issuecomment-527723675
